from typing import Dict, Any
from datetime import datetime


def reporter_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """Generate comprehensive investigation report"""
    indicators = state.get("indicators", [])
    risk_score = state.get("risk_score", 0)
    confidence = state.get("confidence", 0)
    recommendations = state.get("recommendations", [])
    gemini_analysis = state.get("gemini_analysis", "")
    raw_intel = state.get("raw_intel", {})
    executed_actions = state.get("executed_actions", [])
    investigation_id = state.get("investigation_id", "unknown")
    timestamp = state.get("timestamp", datetime.now().isoformat())

    severity = "LOW"
    if risk_score >= 80:
        severity = "CRITICAL"
    elif risk_score >= 60:
        severity = "HIGH"
    elif risk_score >= 40:
        severity = "MEDIUM"

    vt_summary = []
    vt_data = raw_intel.get("virustotal", {})
    for value, data in vt_data.items():
        stats = data.get("stats", {})
        vt_summary.append(
            f"- {value}: {stats.get('malicious', 0)} malicious, {stats.get('suspicious', 0)} suspicious"
        )

    abuse_summary = []
    abuse_data = raw_intel.get("abuseipdb", {})
    for value, data in abuse_data.items():
        abuse_summary.append(
            f"- {value}: {data.get('abuse_confidence_score', 0)}% confidence, {data.get('total_reports', 0)} reports"
        )

    shodan_summary = []
    shodan_data = raw_intel.get("shodan", {})
    for value, data in shodan_data.items():
        ports = data.get("ports", [])
        shodan_summary.append(
            f"- {value}: {len(ports)} open ports, {data.get('org', 'Unknown')}"
        )

    report = f"""
# Threat Intelligence Report

## Investigation Details
- **ID**: {investigation_id}
- **Date**: {timestamp}
- **Status**: {state.get("status", "completed")}

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Risk Score | {risk_score:.1f}/100 |
| Severity | {severity} |
| Confidence | {confidence:.1%} |
| Indicators | {len(indicators)} |

---

## Indicators Analyzed

{chr(10).join([f"- **{ind.get('type').upper()}**: {ind.get('value')}" for ind in indicators])}

---

## Intelligence Findings

### VirusTotal
{vt_summary[0] if vt_summary else "No data available"}
{chr(10).join(vt_summary[1:]) if len(vt_summary) > 1 else ""}

### AbuseIPDB
{abuse_summary[0] if abuse_summary else "No data available"}
{chr(10).join(abuse_summary[1:]) if len(abuse_summary) > 1 else ""}

### Shodan
{shodan_summary[0] if shodan_summary else "No data available"}
{chr(10).join(shodan_summary[1:]) if len(shodan_summary) > 1 else ""}

---

## AI Analysis

{gemini_analysis}

---

## Recommendations

{chr(10).join([f"{i + 1}. {rec}" for i, rec in enumerate(recommendations)])}

---

## Actions Taken

{chr(10).join([f"- {action.get('action')}: {action.get('simulated_action', 'completed')}" for action in executed_actions]) if executed_actions else "No actions executed"}

---

*Report generated by ThreatIntel Agent*
"""

    state["report"] = report
    state["status"] = "completed"

    return state
